### ISSUE TITLE
TODO: Automate Database Monitoring setup

### ISSUE THREAD

**Issue by vitabaks** [vitabaks/postgresql_cluster#249]
- [ ] Netdata
  - [ ] System
  - [ ] Postgres
  - [ ] Patroni (services / Rest API)
  - [ ] Cluster components (etcd, consul, haproxy, confd, keepalived, vip-manager, pgbouncer)
- [ ] Pgwatch (vitabaks/Postgresai edition)
  - https://gitlab.com/postgres-ai/pgwatch2

**Comment by vitabaks** [comment]
https://gitlab.com/postgres-ai/pgwatch2

**Comment by vitabaks** [comment]
If you're interested in this feature, please consider becoming a [sponsor](https://postgresql-cluster.org/sponsor).

**Comment by vitabaks** [comment]
Netdata module: **sql** - for custom SQL metrics.

https://learn.netdata.cloud/docs/collecting-metrics/databases/sql-databases-generic
