### ISSUE TITLE
Resolve all linter issues (ansible-lint, yamllint, flake8)

### ISSUE THREAD

**Issue by ThomasSanson** [vitabaks/postgresql_cluster#308]
## Issue Description
We have discovered that our codebase has a number of issues detected by various linters: ansible-lint, yamllint, and flake8. In order to maintain high code quality and consistency across the project, we need to address these issues.

## Task

- [ ] Review and fix all ansible-lint issues
- [ ] Review and fix all yamllint issues
- [ ] Review and fix all flake8 issues

## Additional Information

1. ansible-lint: This linter checks the Ansible playbooks and roles for best practices and potential errors. For more information, please check the [ansible-lint documentation](https://ansible-lint.readthedocs.io/en/latest/).

2. yamllint: This linter checks YAML files for syntax errors, indentation, and other stylistic issues. For more information, please check the [yamllint documentation](https://yamllint.readthedocs.io/en/stable/).

3. flake8: This linter checks Python code for compliance with PEP8, syntax errors, and other code quality issues. For more information, please check the [flake8 documentation](https://flake8.pycqa.org/en/latest/).

Please make sure to configure the linters with the appropriate configuration files and rules for our project. Submit a pull request with the necessary changes and fixes, and make sure the continuous integration pipeline passes without any issues.

**Comment by vitabaks** [comment]
> Review and fix all ansible-lint issues

In any case, we should not 100% follow all the recommendations of linters, for example, we do not use "fqcn-builtins" to support compatibility with ansible below version 10.

**Comment by ThomasSanson** [comment]
@vitabaks 

Sure, I'll be making updates as I work through the linters.

I believe it's important to follow all linter rules and handle exceptions at the source of the problem. I can show you if needed.

But, why keep so much backward compatibility with ansible-core 2.10? We're at 2.14 now.

Same for Python, we're at 3.10 for the package.

For the collection transition, we'll need ansible-core 2.11 to use the playbooks.

I think keeping compatibility for the last 2 or 3 versions of ansible and Python is enough.

We set dependencies in the requirements.txt file and add virtual environments, so users should have no issues.

Let me know why you want to stay compatible, and we can find a solution.

**Comment by vitabaks** [comment]
> But, why keep so much backward compatibility with ansible-core 2.10? We're at 2.14 now.

I stuck to the versions that can be installed from the standard Linux repository. But, if we recommend installation via pip then there should be no problem with having an older version of ansible on the client side.

> For the collection transition, we'll need ansible-core 2.11 to use the playbooks.

Yes, it looks like we will have to raise the minimum supported ansible version if we switch to the collection format.
